//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetPing_modern.Resources.Views.Blog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetPing_modern.Resources.Views.Blog.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string BlogTitle {
            get {
                return ResourceManager.GetString("BlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records..
        /// </summary>
        public static string ErrorNoPostsMessage {
            get {
                return ResourceManager.GetString("ErrorNoPostsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is not found..
        /// </summary>
        public static string ErrorPostDoesntExistMessage {
            get {
                return ResourceManager.GetString("ErrorPostDoesntExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netping Company&apos;s Blog, Netping Company&apos;s News, Examples of Using Netping Devices, FAQ about Netping Devices.
        /// </summary>
        public static string Page_description {
            get {
                return ResourceManager.GetString("Page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netping&apos;s Blog, Netping&apos;s News, Netping FAQ, Examples of Using Netping.
        /// </summary>
        public static string Page_keywords {
            get {
                return ResourceManager.GetString("Page_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetPing Company&apos;s Blog: Our News, Examples of Using, FAQ.
        /// </summary>
        public static string Page_title {
            get {
                return ResourceManager.GetString("Page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top popular.
        /// </summary>
        public static string PopularArticlesTitle {
            get {
                return ResourceManager.GetString("PopularArticlesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All categories.
        /// </summary>
        public static string TXT_all_categories {
            get {
                return ResourceManager.GetString("TXT_all_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tags.
        /// </summary>
        public static string TXT_all_tags {
            get {
                return ResourceManager.GetString("TXT_all_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string TXT_calendar {
            get {
                return ResourceManager.GetString("TXT_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string TXT_category {
            get {
                return ResourceManager.GetString("TXT_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look for....
        /// </summary>
        public static string TXT_Look_for {
            get {
                return ResourceManager.GetString("TXT_Look_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main tags.
        /// </summary>
        public static string TXT_main_tags {
            get {
                return ResourceManager.GetString("TXT_main_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TXT_tags {
            get {
                return ResourceManager.GetString("TXT_tags", resourceCulture);
            }
        }
    }
}
