//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetPing_modern.Resources.Views.Catalog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetPing_modern.Resources.Views.Catalog.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetPing devices catalog.
        /// </summary>
        public static string Page_title {
            get {
                return ResourceManager.GetString("Page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP SENSORS&lt;br/&gt;MONITORING.
        /// </summary>
        public static string Sec_monitoring {
            get {
                return ResourceManager.GetString("Sec_monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoutly, by IP network  monitoring temperature, humidity, doors and other sensors.
        /// </summary>
        public static string Sec_monitoring_descr {
            get {
                return ResourceManager.GetString("Sec_monitoring_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOTE POWER&lt;br/&gt;CONTROL.
        /// </summary>
        public static string Sec_power {
            get {
                return ResourceManager.GetString("Sec_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP PDU devices for remote power control servers, routers and other network devices.
        /// </summary>
        public static string Sec_power_descr {
            get {
                return ResourceManager.GetString("Sec_power_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string Sec_sub_access {
            get {
                return ResourceManager.GetString("Sec_sub_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Sec_sub_devices {
            get {
                return ResourceManager.GetString("Sec_sub_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string Sec_sub_sensors {
            get {
                return ResourceManager.GetString("Sec_sub_sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready solutions.
        /// </summary>
        public static string Sec_sub_solutions {
            get {
                return ResourceManager.GetString("Sec_sub_solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETHERNET SWITCH&lt;br/&gt;AND POE DEVICES.
        /// </summary>
        public static string Sec_switch {
            get {
                return ResourceManager.GetString("Sec_switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet switchs, and POE (pover over Ethernet) devices.
        /// </summary>
        public static string Sec_switch_descr {
            get {
                return ResourceManager.GetString("Sec_switch_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Txt_compare {
            get {
                return ResourceManager.GetString("Txt_compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare device.
        /// </summary>
        public static string Txt_compare_dev {
            get {
                return ResourceManager.GetString("Txt_compare_dev", resourceCulture);
            }
        }
    }
}
