//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetPing_modern.Resources.Views.MainPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetPing_modern.Resources.Views.MainPage.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental monitoring devices for server rooms, IP PDU.
        /// </summary>
        public static string Page_description {
            get {
                return ResourceManager.GetString("Page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temperature sensors, humidiry sensors, IP PDU.
        /// </summary>
        public static string Page_keywords {
            get {
                return ResourceManager.GetString("Page_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetPing devices.
        /// </summary>
        public static string Page_title {
            get {
                return ResourceManager.GetString("Page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP sensors&lt;br/&gt;monitoring.
        /// </summary>
        public static string Sec_monitoring {
            get {
                return ResourceManager.GetString("Sec_monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoutly, by IP network  monitoring temperature, humidity, doors and other sensors.
        /// </summary>
        public static string Sec_monitoring_descr {
            get {
                return ResourceManager.GetString("Sec_monitoring_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote power&lt;br/&gt;control.
        /// </summary>
        public static string Sec_power {
            get {
                return ResourceManager.GetString("Sec_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP PDU devices for remote power control servers, routers and other network devices.
        /// </summary>
        public static string Sec_power_descr {
            get {
                return ResourceManager.GetString("Sec_power_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet switches&lt;br/&gt;and POE devices.
        /// </summary>
        public static string Sec_switch {
            get {
                return ResourceManager.GetString("Sec_switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet switchs, and POE (pover over Ethernet) devices.
        /// </summary>
        public static string Sec_switch_descr {
            get {
                return ResourceManager.GetString("Sec_switch_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New models.
        /// </summary>
        public static string Title_new_devices {
            get {
                return ResourceManager.GetString("Title_new_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Title_news {
            get {
                return ResourceManager.GetString("Title_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models details.
        /// </summary>
        public static string Txt_models {
            get {
                return ResourceManager.GetString("Txt_models", resourceCulture);
            }
        }
    }
}
