//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetPing_modern.Resources.Views.Product_item {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetPing_modern.Resources.Views.Product_item.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Page_title {
            get {
                return ResourceManager.GetString("Page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Path_main {
            get {
                return ResourceManager.GetString("Path_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string Sec_examples {
            get {
                return ResourceManager.GetString("Sec_examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Sec_faq {
            get {
                return ResourceManager.GetString("Sec_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Sec_files {
            get {
                return ResourceManager.GetString("Sec_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification.
        /// </summary>
        public static string Sec_spec {
            get {
                return ResourceManager.GetString("Sec_spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected:.
        /// </summary>
        public static string Title_connected {
            get {
                return ResourceManager.GetString("Title_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string Title_connected_acces {
            get {
                return ResourceManager.GetString("Title_connected_acces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string Title_connected_sensors {
            get {
                return ResourceManager.GetString("Title_connected_sensors", resourceCulture);
            }
        }
    }
}
