//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetPing_modern.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetPing_modern.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b033f769-447f-41ca-aea9-b5fdd4f08c51.
        /// </summary>
        internal static string Guid_Destination_Global {
            get {
                return ResourceManager.GetString("Guid_Destination_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to df43eb79-0188-4c6e-9f27-af9f608d3505.
        /// </summary>
        internal static string Guid_Destination_Russia {
            get {
                return ResourceManager.GetString("Guid_Destination_Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c8dad096-9557-471d-86e1-52734f83bb47.
        /// </summary>
        internal static string Guid_Label_Archive {
            get {
                return ResourceManager.GetString("Guid_Label_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4d2b1d0b-a53c-4f1c-87e0-f184be81a1ca.
        /// </summary>
        internal static string Guid_Label_EOL {
            get {
                return ResourceManager.GetString("Guid_Label_EOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 85495730-1b83-4188-b351-4fd4970ec6c1.
        /// </summary>
        internal static string Guid_Label_New {
            get {
                return ResourceManager.GetString("Guid_Label_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dada0dc6-3506-4443-85e7-d731ccd169e5.
        /// </summary>
        internal static string Guid_SiteTexts_About {
            get {
                return ResourceManager.GetString("Guid_SiteTexts_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ed0ca003-156e-4708-8bfb-8648fe735b74.
        /// </summary>
        internal static string Guid_SiteTexts_BankDetails {
            get {
                return ResourceManager.GetString("Guid_SiteTexts_BankDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5a4da33b-c7cc-4941-a164-028c45fcf956.
        /// </summary>
        internal static string Guid_SiteTexts_Contacts {
            get {
                return ResourceManager.GetString("Guid_SiteTexts_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d1121469-b2ad-4f73-a2a2-f738cd043520.
        /// </summary>
        internal static string Guid_SiteTexts_OfficeAddress {
            get {
                return ResourceManager.GetString("Guid_SiteTexts_OfficeAddress", resourceCulture);
            }
        }
    }
}
