//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetPing_modern.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Camls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Camls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetPing_modern.Resources.Camls", typeof(Camls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;View&gt;
        ///    &lt;Query&gt;
        ///       &lt;Where&gt;
        ///          &lt;Or&gt;
        ///             &lt;In&gt;
        ///                &lt;FieldRef Name=&apos;Destination&apos; /&gt;
        ///                  &lt;Values&gt;  &lt;Value Type=&apos;TaxonomyFieldType&apos;&gt;Global&lt;/Value&gt;&lt;/Values&gt;
        ///             &lt;/In&gt;
        ///             &lt;In&gt;
        ///                &lt;FieldRef Name=&apos;Destination&apos; /&gt;
        ///                 &lt;Values&gt;  &lt;Value Type=&apos;TaxonomyFieldType&apos;&gt;ALL&lt;/Value&gt; &lt;/Values&gt;                                                
        ///                &lt;/In&gt;
        ///         &lt;/Or&gt;
        ///       &lt;/Where&gt;
        ///       &lt;OrderBy&gt;
        ///		&lt;FieldRef Na [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Caml_Device_keys {
            get {
                return ResourceManager.GetString("Caml_Device_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;View&gt;
        ///                                    &lt;Query&gt;
        ///                                    &lt;Where&gt;
        ///                                            &lt;Or&gt;
        ///                                                &lt;In&gt;
        ///                                                    &lt;FieldRef Name=&apos;Language&apos; /&gt;
        ///                                                    &lt;Values&gt;
        ///                                                        &lt;Value Type=&apos;TaxonomyFieldType&apos;&gt;English&lt;/Value&gt;
        ///                                                    &lt;/Values&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Caml_DevicePhotos {
            get {
                return ResourceManager.GetString("Caml_DevicePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;View&gt;&lt;OrderBy&gt;
        ///                                            &lt;FieldRef Name=&apos;Created&apos; Ascending=&apos;FALSE&apos; /&gt;
        ///                                  &lt;/OrderBy&gt;
        ///                                    &lt;Query&gt;
        ///                                    &lt;Where&gt;
        ///                                        &lt;And&gt;
        ///                                            &lt;Or&gt;
        ///                                                &lt;In&gt;
        ///                                                    &lt;FieldRef Name=&apos;Language&apos; /&gt;
        ///                                    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Caml_Photos_to_pub {
            get {
                return ResourceManager.GetString("Caml_Photos_to_pub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;View&gt;&lt;OrderBy&gt;
        ///                                            &lt;FieldRef Name=&apos;Created&apos; Ascending=&apos;FALSE&apos; /&gt;
        ///                                  &lt;/OrderBy&gt;
        ///                                    &lt;Query&gt;
        ///                                    &lt;Where&gt;
        ///                                        &lt;And&gt;
        ///                                            &lt;Or&gt;
        ///                                                &lt;In&gt;
        ///                                                    &lt;FieldRef Name=&apos;Language&apos; /&gt;
        ///                                    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Caml_Posts {
            get {
                return ResourceManager.GetString("Caml_Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;View&gt;&lt;OrderBy&gt;
        ///                                            &lt;FieldRef Name=&apos;Created&apos; Ascending=&apos;FALSE&apos; /&gt;
        ///                                  &lt;/OrderBy&gt;
        ///                                    &lt;Query&gt;
        ///                                    &lt;Where&gt;
        ///                                        &lt;And&gt;
        ///                                            &lt;Or&gt;
        ///                                                &lt;In&gt;
        ///                                                    &lt;FieldRef Name=&apos;Language&apos; /&gt;
        ///                                    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Caml_Pub_files {
            get {
                return ResourceManager.GetString("Caml_Pub_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;View&gt;
        ///                                    &lt;Query&gt;
        ///                                    &lt;Where&gt;
        ///                                            &lt;Or&gt;
        ///                                                &lt;In&gt;
        ///                                                    &lt;FieldRef Name=&apos;Language&apos; /&gt;
        ///                                                    &lt;Values&gt;
        ///                                                        &lt;Value Type=&apos;TaxonomyFieldType&apos;&gt;English&lt;/Value&gt;
        ///                                                    &lt;/Values&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Caml_SiteTexts {
            get {
                return ResourceManager.GetString("Caml_SiteTexts", resourceCulture);
            }
        }
    }
}
