//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetPing_modern.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Header {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Header() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetPing_modern.Resources.Views.Shared.Header", typeof(Header).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netping device accessories.
        /// </summary>
        public static string Category_access {
            get {
                return ResourceManager.GetString("Category_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors monitorings, IPsensors.
        /// </summary>
        public static string Category_monitoring {
            get {
                return ResourceManager.GetString("Category_monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP PDU, remote power control units.
        /// </summary>
        public static string Category_power_control {
            get {
                return ResourceManager.GetString("Category_power_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netping devices sensors.
        /// </summary>
        public static string Category_sensors {
            get {
                return ResourceManager.GetString("Category_sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet switchs and POE devices.
        /// </summary>
        public static string Category_switch {
            get {
                return ResourceManager.GetString("Category_switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question.
        /// </summary>
        public static string Header_ask {
            get {
                return ResourceManager.GetString("Header_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sales@netpingdevice.com.
        /// </summary>
        public static string Header_email_sales {
            get {
                return ResourceManager.GetString("Header_email_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@netpingdevice.com.
        /// </summary>
        public static string Header_email_support {
            get {
                return ResourceManager.GetString("Header_email_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods in the basket.
        /// </summary>
        public static string Header_goods_in_basket {
            get {
                return ResourceManager.GetString("Header_goods_in_basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +886-2-23121582.
        /// </summary>
        public static string Header_phone {
            get {
                return ResourceManager.GetString("Header_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To buy.
        /// </summary>
        public static string Header_to_buy {
            get {
                return ResourceManager.GetString("Header_to_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices for monitoring of server rooms and remote power management.
        /// </summary>
        public static string Logo_Title {
            get {
                return ResourceManager.GetString("Logo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_about {
            get {
                return ResourceManager.GetString("Menu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Menu_blog {
            get {
                return ResourceManager.GetString("Menu_blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to buy.
        /// </summary>
        public static string Menu_buy {
            get {
                return ResourceManager.GetString("Menu_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy directly.
        /// </summary>
        public static string Menu_buy_directly {
            get {
                return ResourceManager.GetString("Menu_buy_directly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to partnership.
        /// </summary>
        public static string Menu_buy_partner_howto {
            get {
                return ResourceManager.GetString("Menu_buy_partner_howto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy from partners.
        /// </summary>
        public static string Menu_buy_partners {
            get {
                return ResourceManager.GetString("Menu_buy_partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Menu_contacts {
            get {
                return ResourceManager.GetString("Menu_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Menu_faq {
            get {
                return ResourceManager.GetString("Menu_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netping news.
        /// </summary>
        public static string Menu_news {
            get {
                return ResourceManager.GetString("Menu_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        public static string Menu_solutions {
            get {
                return ResourceManager.GetString("Menu_solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Menu_support {
            get {
                return ResourceManager.GetString("Menu_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our vacancy.
        /// </summary>
        public static string Menu_vacancy {
            get {
                return ResourceManager.GetString("Menu_vacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
    }
}
